services:
  db:
    image: mysql:latest
    container_name: local-mysql-golang
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: passwordje
      MYSQL_DATABASE: golang
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: always
